export {
  AUTHORING_HTTP_OPERATIONS,
  AUTHORING_HTTP_OPERATIONS_BY_ROUTE,
  AUTHORING_HTTP_SCHEMA_ID,
  createHttpHostAdapter,
  HTTP_HOST_OPERATION_ROUTES,
  type AuthoringHttpOperationContract,
  type AuthoringHttpOperationRegistry,
  type AuthoringHttpRoute,
  type ConfiguredHttpHostAdapterOptions,
  type HttpAuthenticationConfiguration,
  type HttpAuthenticationRequest,
  type HttpAuthenticationResolver,
  type HttpBearerTokenAuthentication,
  type HttpFetchLike,
  type HttpHeaderTokenAuthentication,
  type HttpHostAdapterOptions,
  type HttpHostOperationEndpoints,
  type HttpHostOperationRoute,
  type HttpHostRoutingConfiguration,
  type HttpHostTransportConfiguration,
  type HttpRequestInit,
  type HttpResponseLike,
  type HttpSameOriginSessionAuthentication,
  type HttpSchemaValidator,
  type HttpTimeoutHandle,
} from '@kumwe/studio-core';
export {
  createBrowserHttpHostAdapter,
  type BrowserConfiguredHttpHostAdapterOptions,
  type BrowserHttpHostAdapterOptions,
  type BrowserLocationSnapshot,
} from './browser-http-host-adapter.js';
