export {
  isHostPortError,
  isPreviewMarker,
  isPreviewMessage,
  isPreviewRenderedPayload,
} from './guards.js';
export { HostPortFailure, isHostPortFailure } from './host-failure.js';
export {
  authoringHttpSchema,
  authoringHttpVectorSchema,
  authoringMessageCatalogSchema,
  authoringSaveSchema,
  authoringSessionSchema,
  authoringTargetSchema,
  authoringWebVectorSchema,
  blockDefinitionSchema,
  bindingProjectionVectorSchema,
  blueprintSchema,
  commandSchema,
  commandVectorSchema,
  canonicalVectorSchema,
  commonSchema,
  contentModelSchema,
  corpusManifestSchema,
  designVocabularySchema,
  entrySchema,
  fieldAdapterSchema,
  hostCapabilitiesSchema,
  hostErrorSchema,
  hostOperationsSchema,
  hostRequestSchema,
  hostResultSchema,
  hostVectorSchema,
  hostSequenceVectorSchema,
  inspectorSchema,
  mediaAssetSchema,
  mediaReferenceSchema,
  mediaUploadGrantSchema,
  mediaUploadSessionSchema,
  mediaVectorSchema,
  migrationSchema,
  patternSchema,
  pluginManifestSchema,
  previewMessageSchema,
  previewVectorSchema,
  rendererWebVectorSchema,
  protocolSchemas,
  provenanceSchema,
  richTextProjectionSchema,
  richTextSchema,
  reusableContentTypeSchema,
  schemaProfileSchema,
  schemaProfileVectorSchema,
  studioBrowserAssetsSchema,
  studioConfigurationSchema,
  studioDeploymentSchema,
  studioChartSchema,
  studioDrawingSchema,
  studioMoneySchema,
  studioPresentationSchema,
  studioReleaseSchema,
  studioTableSchema,
  themeSchema,
  unresolvedContributionSchema,
} from './schemas.js';
export {
  GENERATED_PROTOCOL_SCHEMA_FILES,
  GENERATED_TYPESCRIPT_MODEL_METADATA,
  roundTripGeneratedProtocolModel,
} from './generated/schema-models.js';
export type * from './generated/schema-models.js';
export {
  STUDIO_CONTRACT_VERSION,
  STUDIO_STALE_SESSION_GENERATION_DIAGNOSTIC_CODE,
  STUDIO_WIRE_PROTOCOL_VERSION,
  type AddModelFieldCommand,
  type AddModelFieldPayload,
  type ApplyPatternCommand,
  type ApplyPatternPayload,
  type ArtifactPort,
  type ArtifactReference,
  type AuthoringAffectedArtifact,
  type AuthoringArtifactCoordinates,
  type AuthoringArtifactState,
  type AuthoringCapabilityRequirement,
  type AuthoringContributionDependency,
  type AuthoringContributionKind,
  type AuthoringDirtyArtifact,
  type AuthoringPort,
  type AuthoringPresentationState,
  type AuthoringReturnContext,
  type AuthoringSaveAsNewTypeDraft,
  type AuthoringSaveAsNewTypeRequest,
  type AuthoringSaveDraft,
  type AuthoringSaveIntent,
  type AuthoringSaveItemDraft,
  type AuthoringSaveItemRequest,
  type AuthoringSaveNewTypeVersionDraft,
  type AuthoringSaveNewTypeVersionRequest,
  type AuthoringSaveOutcome,
  type AuthoringSavePlan,
  type AuthoringSavePlanReference,
  type AuthoringSaveResult,
  type AuthoringSessionCapabilities,
  type AuthoringSessionPresentation,
  type AuthoringSessionSnapshot,
  type AuthoringStartKind,
  type AuthoringStartRequest,
  type AuthoringStartSource,
  type AuthoringTargetDeclaration,
  type AuthoringTargetEligibility,
  type AuthoringTargetResolution,
  type AuthoringTargetResolveRequest,
  type AuthoringTypeListPage,
  type AuthoringTypeListQuery,
  type AuthoringTypeSummary,
  type BatchCommand,
  type BatchOperation,
  type BatchPayload,
  type BindingSource,
  type BindingTransform,
  type BlockAccessibilityContract,
  type BlockDefinition,
  type BlockFallback,
  type BlockIcon,
  type BlockPortDefinition,
  type BlockPortAuthoringMetadata,
  type BlockPropertyControl,
  type BlockSlotAcceptance,
  type BlockSlotDefinition,
  type BlockType,
  type BlueprintBatchOperation,
  type BlueprintBlockLock,
  type BlueprintCommand,
  type BlueprintDependencyLock,
  type BlueprintDocument,
  type BlueprintNode,
  type CommandBase,
  type CommandDestination,
  type ContextValueBindingSource,
  type ContentFieldKind,
  type ContentModelDocument,
  type ContentModelEnumValue,
  type DesignVocabulary,
  type DiagnosticLocation,
  type DuplicateNodeCommand,
  type DuplicateNodePayload,
  type EntryDocument,
  type EntryFieldBindingSource,
  type ExperimentalShellConfiguration,
  type ExtensionLifecycleState,
  type FieldAuthoringMetadata,
  type FieldAdapterContribution,
  type FieldBinding,
  type FieldConstraints,
  type FieldDefinition,
  type HostAdapter,
  type HostCapabilities,
  type HostErrorCategory,
  type HostFeatureCapability,
  type HostPortCapability,
  type HostPortError,
  type HostPortResult,
  type HostRequestContext,
  type InsertNodeCommand,
  type InsertNodePayload,
  type InspectorContribution,
  type JsonObject,
  type JsonPrimitive,
  type JsonSchema,
  type JsonValue,
  type LocalizationPort,
  type LocalName,
  type LockedArtifactReference,
  type MediaAsset,
  type MediaAccessibility,
  type MediaHostPort,
  type MediaCropIntent,
  type MediaMetadata,
  type MediaPage,
  type MediaQuery,
  type MediaReference,
  type MediaRendition,
  type MediaRenditionIntent,
  type MediaUploadAcceptedAsset,
  type MediaUploadGrant,
  type MediaUploadPlan,
  type MediaUploadProgress,
  type MediaUploadRequestDescriptor,
  type MediaUploadSession,
  type MediaUploadSessionState,
  type MessageReference,
  type MigrationArtifactKind,
  type MigrationDeclaration,
  type ModelPort,
  type MoveNodeCommand,
  type MoveNodePayload,
  type NodeAuthoringPolicy,
  type NodeId,
  type OwnerReference,
  type PackageRelativePath,
  type PatternDocument,
  type PatternReference,
  type PermissionExplanation,
  type PermissionPort,
  type PermissionSnapshot,
  type PluginActivation,
  type PluginCapabilityRequirement,
  type PluginContributionDeclaration,
  type PluginContributionKind,
  type PluginDependency,
  type PluginEntryModule,
  type PluginEntryRealm,
  type PluginManifest,
  type PreviewActivatedMessage,
  type PreviewActivatedPayload,
  type PreviewDisposeMessage,
  type PreviewDisposePayload,
  type PreviewErrorMessage,
  type PreviewErrorPayload,
  type PreviewMarkerRect,
  type PreviewMeasureMessage,
  type PreviewMeasurePayload,
  type PreviewMeasurementsMessage,
  type PreviewMeasurementsPayload,
  type PreviewMessage,
  type PreviewMessageBase,
  type PreviewPort,
  type PreviewReadyMessage,
  type PreviewReadyPayload,
  type PreviewReloadMessage,
  type PreviewReloadPayload,
  type PreviewRenderMessage,
  type PreviewRenderedMessage,
  type PreviewRenderedPayload,
  type PreviewRenderPayload,
  type PreviewSelectMessage,
  type PreviewSelectPayload,
  type PreviewTeardownMessage,
  type PreviewTeardownPayload,
  type PreviewViewportMessage,
  type PreviewViewportMetrics,
  type PreviewViewportPayload,
  type ProvenanceActor,
  type ProvenanceEntry,
  type ProvenanceOrigin,
  type ProvenanceRecord,
  type QualifiedName,
  type QueryReferenceBindingSource,
  type RecoveryPort,
  type RelationshipAuthoringMetadata,
  type RelationshipDefinition,
  type RemoveBindingCommand,
  type RemoveBindingPayload,
  type RemoveNodeCommand,
  type RemoveNodePayload,
  type RendererRequirement,
  type ReorderChildrenCommand,
  type ReorderChildrenPayload,
  type ResetInheritedPropertyCommand,
  type ResetInheritedPropertyPayload,
  type ResourcePort,
  type ResourceReferenceBindingSource,
  type ResourceSearchHit,
  type ResourceSearchPage,
  type ResourceSearchQuery,
  type ResolvedEntryReference,
  type ReusableContentTypeAuthoringPolicy,
  type ReusableContentTypeDefinition,
  type ReusableContentTypeReference,
  type RestoreNodeCommand,
  type RestoreNodePayload,
  type Revision,
  type SemanticVersion,
  type SetBindingCommand,
  type SetBindingPayload,
  type SetFieldValueCommand,
  type SetFieldValuePayload,
  type SetPropertyCommand,
  type SetPropertyPayload,
  type SetSizeRoleCommand,
  type SetSizeRolePayload,
  type SizeRoleAxis,
  type SlotCompositionPolicy,
  type StableId,
  type StaticValueBindingSource,
  type StudioArtifact,
  type StudioAuthoringMode,
  type StudioCommand,
  type StudioConfiguration,
  type StudioContractVersion,
  type StudioDeploymentAuthentication,
  type StudioDeploymentBearerTokenAuthentication,
  type StudioDeploymentConfiguration,
  type StudioDeploymentConfigurationBase,
  type StudioDeploymentContributionBundle,
  type StudioDeploymentContributionPayload,
  type StudioDeploymentHeaderTokenAuthentication,
  type StudioDeploymentHttpTransport,
  type StudioDeploymentLaunch,
  type StudioDeploymentOperationEndpoints,
  type StudioDeploymentOperationMapRouting,
  type StudioDeploymentOperationRoute,
  type StudioDeploymentRouting,
  type StudioDeploymentSameOriginSessionAuthentication,
  type StudioDeploymentSingleEndpointRouting,
  type StudioDeploymentStandaloneTransport,
  type StudioDeploymentTransport,
  type StudioHostedDeploymentConfiguration,
  type StudioStandaloneDeploymentConfiguration,
  type StudioChartDataset,
  type StudioChartSpec,
  type StudioDrawingDocument,
  type StudioDrawingPoint,
  type StudioDrawingStroke,
  type StudioMoneyValue,
  type StudioPresentationIntent,
  type StudioTableDocument,
  type StudioDiagnostic,
  type StudioDisplayPreferences,
  type StudioLimits,
  type StudioResourceContext,
  type StudioResourceScope,
  type StudioSessionMode,
  type StudioWireProtocolVersion,
  type TelemetryEvent,
  type TelemetryPort,
  type ThemeAlias,
  type ThemeBlockSupport,
  type ThemeDesignChoice,
  type ThemeDesignControl,
  type ThemeDesignControlKind,
  type ThemeDocument,
  type ThemeRecipe,
  type ThemeRendererDeclaration,
  type ThemeViewport,
  type UnresolvedContribution,
  type UnresolvedContributionReason,
  type UnresolvedContributionReference,
  type UnsetPropertyCommand,
  type UnsetPropertyPayload,
  type UnsetSizeRoleCommand,
  type UnsetSizeRolePayload,
} from './types.js';
